#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd2d;
constexpr uint24_t FX_DATA_BYTES = 180790;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t bananatree = 0x000000;
constexpr uint24_t deathattackleft = 0x0032A2;
constexpr uint24_t deathattackright = 0x0092A4;
constexpr uint24_t deathdissolveleft = 0x00F2A6;
constexpr uint24_t deathdissolveright = 0x0152A8;
constexpr uint24_t deathhitleft = 0x01B2AA;
constexpr uint24_t deathhitright = 0x01CAAC;
constexpr uint24_t deathidleleft = 0x01E2AE;
constexpr uint24_t deathidleright = 0x0242B0;
constexpr uint24_t HUDBoss = 0x02A2B2;
constexpr uint24_t punklogooutlined = 0x02AA34;
